### ISSUE TITLE
[Question] What about clustering?

### ISSUE THREAD

**Issue by MarcMagnin** [Restream/reindexer#4]
Hi,

Thanks for such a nice project! Do you plan to add clustering/distributed features?

Many thanks!

**Comment by igtulm** [comment]
Hello.

First of all, we are going to implement a custom binary protocol for client-server communications. After that we will consider about the asynchronous replication functionality using WAL (write ahead logging) techniques. This will allow us to horizontally scale reads at the Reindexer level.
There is a limitation with the current architecture: a single table must fit in memory of the first server. We don't plan to implement sharding, because it will cause a Reindexer's performance decrease.
